# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(451, 582)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.userName = QtWidgets.QLineEdit(self.centralwidget)
        self.userName.setGeometry(QtCore.QRect(40, 20, 181, 31))
        self.userName.setObjectName("userName")
        self.phoneNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.phoneNumber.setGeometry(QtCore.QRect(240, 20, 181, 31))
        self.phoneNumber.setObjectName("phoneNumber")
        self.mainTable = QtWidgets.QTableWidget(self.centralwidget)
        self.mainTable.setGeometry(QtCore.QRect(20, 110, 401, 391))
        self.mainTable.setObjectName("mainTable")
        self.mainTable.setColumnCount(2)
        self.mainTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(1, item)
        self.mainTable.horizontalHeader().setVisible(True)
        self.mainTable.horizontalHeader().setStretchLastSection(True)
        self.removeRow = QtWidgets.QPushButton(self.centralwidget)
        self.removeRow.setGeometry(QtCore.QRect(320, 70, 101, 28))
        self.removeRow.setObjectName("removeRow")
        self.addData = QtWidgets.QPushButton(self.centralwidget)
        self.addData.setGeometry(QtCore.QRect(210, 70, 101, 28))
        self.addData.setObjectName("addData")
        mainWindow.setCentralWidget(self.centralwidget)
        self.mainMenubar = QtWidgets.QMenuBar(mainWindow)
        self.mainMenubar.setGeometry(QtCore.QRect(0, 0, 451, 28))
        self.mainMenubar.setObjectName("mainMenubar")
        self.menuFile = QtWidgets.QMenu(self.mainMenubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.mainMenubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.mainMenubar)
        self.menuHelp.setObjectName("menuHelp")
        mainWindow.setMenuBar(self.mainMenubar)
        self.mainStatusbar = QtWidgets.QStatusBar(mainWindow)
        self.mainStatusbar.setObjectName("mainStatusbar")
        mainWindow.setStatusBar(self.mainStatusbar)
        self.mainToolbar = QtWidgets.QToolBar(mainWindow)
        self.mainToolbar.setMovable(False)
        self.mainToolbar.setObjectName("mainToolbar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolbar)
        self.actionExport = QtWidgets.QAction(mainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionImport = QtWidgets.QAction(mainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExit = QtWidgets.QAction(mainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionPreferences = QtWidgets.QAction(mainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAbout = QtWidgets.QAction(mainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAbout)
        self.mainMenubar.addAction(self.menuFile.menuAction())
        self.mainMenubar.addAction(self.menuEdit.menuAction())
        self.mainMenubar.addAction(self.menuHelp.menuAction())
        self.mainToolbar.addAction(self.actionImport)
        self.mainToolbar.addAction(self.actionExport)
        self.mainToolbar.addSeparator()
        self.mainToolbar.addAction(self.actionPreferences)
        self.mainToolbar.addSeparator()
        self.mainToolbar.addAction(self.actionAbout)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Python Data Manager"))
        self.userName.setPlaceholderText(_translate("mainWindow", "Username"))
        self.phoneNumber.setPlaceholderText(_translate("mainWindow", "Phone Number"))
        item = self.mainTable.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Username"))
        item = self.mainTable.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Phone Number"))
        self.removeRow.setText(_translate("mainWindow", "Remove Row"))
        self.addData.setText(_translate("mainWindow", "Add Data"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuEdit.setTitle(_translate("mainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.mainToolbar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.actionExport.setText(_translate("mainWindow", "Export"))
        self.actionImport.setText(_translate("mainWindow", "Import"))
        self.actionExit.setText(_translate("mainWindow", "Exit"))
        self.actionPreferences.setText(_translate("mainWindow", "Preferences"))
        self.actionAbout.setText(_translate("mainWindow", "About"))

